steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_MAPBOX_TOKEN=${_NEXT_PUBLIC_MAPBOX_TOKEN}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/parking-app'
      - '.'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'parking-v2'
      - '--image'
      - 'gcr.io/$PROJECT_ID/parking-app'
      - '--region'
      - 'us-east4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/parking-app'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _NEXT_PUBLIC_MAPBOX_TOKEN: ''
