// NYC parking violation codes — source: NYC Open Data DOF Parking Violation Codes (ncbg-6agr).
// Auto-generated; do not hand-edit. Fine amounts in USD.

export interface ViolationInfo {
  definition: string;
  fineManhattan: number | null;
  fineOther: number | null;
}

export const VIOLATION_CODES: Record<string, ViolationInfo> = {
  '1': { definition: 'Failure to Display Bus Permit', fineManhattan: 515, fineOther: 515 },
  '2': { definition: 'No Operator Nam/add/ph Display', fineManhattan: 515, fineOther: 515 },
  '3': { definition: 'Unauthorized Passenger Pick-up', fineManhattan: 515, fineOther: 515 },
  '4': { definition: 'Bus Parking in Lower Manhattan', fineManhattan: 115, fineOther: 115 },
  '5': { definition: 'Bus Lane Violation', fineManhattan: 250, fineOther: 250 },
  '6': { definition: 'Overnight Tractor Trailer Pkg', fineManhattan: 500, fineOther: 500 },
  '7': { definition: 'Failure to Stop at Red Light', fineManhattan: 50, fineOther: 50 },
  '8': { definition: 'Idling', fineManhattan: 115, fineOther: 115 },
  '9': { definition: 'Obstructing Traffic/intersect', fineManhattan: 115, fineOther: 115 },
  '10': { definition: 'No Stopping-day/time Limits', fineManhattan: 115, fineOther: 115 },
  '11': { definition: 'No Standing-hotel Loading', fineManhattan: 115, fineOther: 115 },
  '12': { definition: 'Mobile Bus Lane Violation', fineManhattan: 250, fineOther: 250 },
  '13': { definition: 'No Standing-taxi Stand', fineManhattan: 115, fineOther: 115 },
  '14': { definition: 'No Standing-day/time Limits', fineManhattan: 115, fineOther: 115 },
  '15': { definition: 'No Standing-off-street Lot', fineManhattan: 115, fineOther: 115 },
  '16': { definition: 'No Standing-exc. Truck Loading', fineManhattan: 95, fineOther: 95 },
  '17': { definition: 'No Standing-exc. Auth. Vehicle', fineManhattan: 95, fineOther: 95 },
  '18': { definition: 'No Standing-bus Lane', fineManhattan: 115, fineOther: 115 },
  '19': { definition: 'No Standing-bus Stop', fineManhattan: 115, fineOther: 115 },
  '20': { definition: 'No Parking-day/time Limits', fineManhattan: 65, fineOther: 60 },
  '21': { definition: 'No Parking-street Cleaning', fineManhattan: 65, fineOther: 65 },
  '22': { definition: 'No Stand Taxi/fhv Relief Stand', fineManhattan: 115, fineOther: 115 },
  '23': { definition: 'No Parking-taxi Stand', fineManhattan: 65, fineOther: 60 },
  '24': { definition: 'No Parking-exc. Auth. Vehicle', fineManhattan: 65, fineOther: 60 },
  '25': { definition: 'No Standing-commuter Van Stop', fineManhattan: 115, fineOther: 115 },
  '26': { definition: 'No Standing-for Hire Veh Stnd', fineManhattan: 115, fineOther: 115 },
  '27': { definition: 'No Parking-exc. Dsblty Permit', fineManhattan: 180, fineOther: 180 },
  '28': { definition: 'Overtime Standing Dp', fineManhattan: 95, fineOther: 95 },
  '29': { definition: 'Altering Intercity Bus Permit', fineManhattan: 515, fineOther: 515 },
  '30': { definition: 'No Stop/standng Except Pas P/u', fineManhattan: 515, fineOther: 515 },
  '31': { definition: 'No Standing-comm Meter Zone', fineManhattan: 115, fineOther: 115 },
  '32': { definition: 'Ot Parking-missing/broken Metr', fineManhattan: 65, fineOther: 35 },
  '33': { definition: 'Misuse Parking Permit', fineManhattan: 65, fineOther: 65 },
  '34': { definition: 'Expired Meter', fineManhattan: 65, fineOther: 35 },
  '35': { definition: 'Selling/offering Mchndse-meter', fineManhattan: 65, fineOther: 35 },
  '36': { definition: 'Phto School Zn Speed Violation', fineManhattan: 50, fineOther: 50 },
  '37': { definition: 'Expired Muni Meter', fineManhattan: 65, fineOther: 35 },
  '38': { definition: 'Fail to Dsply Muni Meter Recpt', fineManhattan: 65, fineOther: 35 },
  '39': { definition: 'Overtime Pkg-time Limit Posted', fineManhattan: 65, fineOther: 60 },
  '40': { definition: 'Fire Hydrant', fineManhattan: 115, fineOther: 115 },
  '41': { definition: 'Miscellaneous', fineManhattan: 0, fineOther: 0 },
  '42': { definition: 'Expired Muni Mtr-comm Mtr Zn', fineManhattan: 65, fineOther: 35 },
  '43': { definition: 'Expired Meter-comm Meter Zone', fineManhattan: 65, fineOther: 35 },
  '44': { definition: 'Pkg in Exc. of Lim-comm Mtr Zn', fineManhattan: 65, fineOther: 35 },
  '45': { definition: 'Traffic Lane', fineManhattan: 115, fineOther: 115 },
  '46': { definition: 'Double Parking', fineManhattan: 115, fineOther: 115 },
  '47': { definition: 'Double Parking-midtown Comml', fineManhattan: 115, fineOther: 115 },
  '48': { definition: 'Bike Lane', fineManhattan: 115, fineOther: 115 },
  '49': { definition: 'Excavation-vehicle Obstr Traff', fineManhattan: 95, fineOther: 95 },
  '50': { definition: 'Crosswalk', fineManhattan: 115, fineOther: 115 },
  '51': { definition: 'Sidewalk', fineManhattan: 115, fineOther: 115 },
  '52': { definition: 'Intersection', fineManhattan: 115, fineOther: 115 },
  '53': { definition: 'Safety Zone', fineManhattan: 115, fineOther: 115 },
  '54': { definition: 'Pckp Dschrge in Prhbtd Zone', fineManhattan: 115, fineOther: 115 },
  '55': { definition: 'Elevated/divided Highway/tunnl', fineManhattan: 115, fineOther: 115 },
  '56': { definition: 'Divided Highway', fineManhattan: 115, fineOther: 115 },
  '57': { definition: 'Weigh in Motion Violation', fineManhattan: 650, fineOther: 650 },
  '58': { definition: 'Marginal Street/water Front', fineManhattan: 65, fineOther: 45 },
  '59': { definition: 'Angle Parking-comm Vehicle', fineManhattan: 115, fineOther: 115 },
  '60': { definition: 'Angle Parking', fineManhattan: 65, fineOther: 45 },
  '61': { definition: 'Wrong Way', fineManhattan: 65, fineOther: 45 },
  '62': { definition: 'Beyond Marked Space', fineManhattan: 65, fineOther: 45 },
  '63': { definition: 'Nighttime Std/ Pkg in a Park', fineManhattan: 95, fineOther: 95 },
  '64': { definition: 'No Standing Excp D/s', fineManhattan: 95, fineOther: 95 },
  '65': { definition: 'Overtime Stdg D/s', fineManhattan: 95, fineOther: 95 },
  '66': { definition: 'Detached Trailer', fineManhattan: 65, fineOther: 45 },
  '67': { definition: 'Pedestrian Ramp', fineManhattan: 165, fineOther: 165 },
  '68': { definition: 'Non-compliance W/ Posted Sign', fineManhattan: 65, fineOther: 60 },
  '69': { definition: 'Fail to Disp. Muni Meter Recpt', fineManhattan: 65, fineOther: 35 },
  '70': { definition: 'Reg. Sticker-expired/missing', fineManhattan: 65, fineOther: 65 },
  '71': { definition: 'Insp. Sticker-expired/missing', fineManhattan: 65, fineOther: 65 },
  '72': { definition: 'Insp Sticker-mutilated/c\'feit', fineManhattan: 65, fineOther: 65 },
  '73': { definition: 'Reg Sticker-mutilated/c\'feit', fineManhattan: 65, fineOther: 65 },
  '74': { definition: 'Front or Back Plate Missing', fineManhattan: 65, fineOther: 65 },
  '75': { definition: 'No Match-plate/sticker', fineManhattan: 65, fineOther: 65 },
  '76': { definition: 'Vin Obscured', fineManhattan: 65, fineOther: 65 },
  '77': { definition: 'Parked Bus-exc. Desig. Area', fineManhattan: 65, fineOther: 45 },
  '78': { definition: 'Nght Pkg on Resid Str-comm Veh', fineManhattan: 65, fineOther: 65 },
  '79': { definition: 'Unauthorized Bus Layover', fineManhattan: 115, fineOther: 115 },
  '80': { definition: 'Missing Equipment', fineManhattan: 60, fineOther: 45 },
  '81': { definition: 'No Standing Excp Dp', fineManhattan: 95, fineOther: 95 },
  '82': { definition: 'Comml Plates-unaltered Vehicle', fineManhattan: 115, fineOther: 115 },
  '83': { definition: 'Improper Registration', fineManhattan: 65, fineOther: 65 },
  '84': { definition: 'Pltfrm Lfts Lwrd Pos Comm Veh', fineManhattan: 65, fineOther: 45 },
  '85': { definition: 'Storage-3hr Commercial', fineManhattan: 65, fineOther: 65 },
  '86': { definition: 'Midtown Pkg or Std-3hr Limit', fineManhattan: 115, fineOther: 115 },
  '87': { definition: 'Fraudulent Use Parking Permit', fineManhattan: 65, fineOther: 65 },
  '88': { definition: 'Unaltered Comm Veh-nme/address', fineManhattan: 115, fineOther: 115 },
  '89': { definition: 'No Std(exc Trks/gmtdst No-trk)', fineManhattan: 115, fineOther: 115 },
  '90': { definition: 'Veh-sale/wshng/rprng/driveway', fineManhattan: 40, fineOther: 25 },
  '91': { definition: 'Vehicle for Sale(dealers Only)', fineManhattan: 65, fineOther: 45 },
  '92': { definition: 'Wash/repair Vehcl-repair Only', fineManhattan: 65, fineOther: 45 },
  '93': { definition: 'Remove/replace Flat Tire', fineManhattan: 65, fineOther: 65 },
  '96': { definition: 'Railroad Crossing', fineManhattan: 95, fineOther: 95 },
  '97': { definition: 'Vacant Lot', fineManhattan: 65, fineOther: 45 },
  '98': { definition: 'Obstructing Driveway', fineManhattan: 95, fineOther: 95 },
  '99': { definition: 'Other', fineManhattan: 105, fineOther: 105 },
};

/** Human-readable label for a violation code, e.g. "No Parking - Street Cleaning (#21)". */
export function violationLabel(code: string): string {
  const info = VIOLATION_CODES[code];
  return info ? info.definition : `Violation code ${code}`;
}

